version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sms-hub-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - sms-hub-network
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: sms-hub-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sms_hub
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: sms_hub
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - sms-hub-network

  redis:
    image: redis:7-alpine
    container_name: sms-hub-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - sms-hub-network

  nginx:
    image: nginx:alpine
    container_name: sms-hub-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sms-hub-network
    depends_on:
      - app

networks:
  sms-hub-network:
    driver: bridge
